# 6. Reduction Operations in NumPy

In [22]:
import numpy as np

For this part, we create a dummy dataset consisting of $200$ rows and $5$ columns by sampling from the uniform distribution  $\mathcal{U}(-10, 10)$.

In [23]:
dataset = np.random.uniform(-10, 10, (200, 5))
print(dataset[:10]) # Print the first 10 rows of our dataset

[[ 5.89104184  4.81845065  3.85891768  3.24041667 -2.25979338]
 [-6.41879884  1.40599835 -3.41659486  5.15972299 -3.08732052]
 [-9.33743353  3.54716258  7.27243894 -8.64463425  1.47705302]
 [ 1.41258219  0.07376224 -4.94991269 -1.87485145 -2.3539806 ]
 [ 7.61656308  1.55349878 -3.52878028 -1.46503808  5.39389527]
 [-6.05493415  5.98326608  9.79123628 -4.26397597 -2.73122217]
 [-9.17282648 -6.85199347  4.54922559 -4.15990553 -9.64086998]
 [ 7.96681397 -1.19181004 -9.96957345  1.58217469 -3.26679247]
 [ 6.11056627  5.72887525  5.01223107  6.36488737 -0.64797884]
 [-0.88627168 -3.64044891 -5.41108438  9.8075354   4.80090553]]


To compute the mean value, we can use the array method `arr.mean()`.

In [24]:
mean = np.mean(dataset) # or dataset.mean()
print(mean)

0.1689345319416897


Sometimes, we want to compute the mean for each column or row. We can do this by specifying which dimension we wish to compute the mean along.

In [25]:
# Compute the mean along axis 1. This will take the mean over all columns for each row
# resulting in an array of shape (200,)
row_means = np.mean(dataset, axis=1) # or dataset.mean(axis=1)
print(row_means.shape) # The mean for each row 
print(row_means[:10])  # Print the mean for the first 10 rows

# Similarly, for computing the mean over all rows
col_means = np.mean(dataset, axis=0) # or dataset.mean(axis=0)
print(col_means.shape)
print(col_means)

(200,)
[ 3.10980669 -1.27139858 -1.13708265 -1.53848006  1.91402775  0.54487401
 -5.05527397 -0.97583746  4.51371622  0.93412719]
(5,)
[ 0.49016245 -0.07680027  0.02311729  0.06389554  0.34429765]


There are similar functions for computing the sum, minimum, maximum and standard deviation of an array. We can also here specify over which axes we want to compute along.

In [26]:
print(np.sum(dataset, axis=0))      # The sum of each column (compute along row-dimension, axis 0)
print(np.max(dataset))              # The largest value in the entire dataset
print(np.min(dataset, axis=1)[:10]) # The smallest values for the 10 first rows (along the column dimension)
print(np.std(dataset, axis=0))      # Standard deviation for each column

[ 98.03248953 -15.36005302   4.62345713  12.77910873  68.85952957]
9.972270780205779
[-2.25979338 -6.41879884 -9.33743353 -4.94991269 -3.52878028 -6.05493415
 -9.64086998 -9.96957345 -0.64797884 -5.41108438]
[5.67155102 5.61129977 6.04381688 5.88828636 5.84572453]


If we want to find the index of the smallest or largest value, we can use `np.argmin()` and `np.argmax()`, respectively. See the following example where we find the index (and value) of the smallest and largest value in the first column of `dataset`.

In [27]:
first_column = dataset[:, 0]      # Select only the first column

min_idx = np.argmin(first_column) # Find the index of the smallest value
min_val = first_column[min_idx]   # Get the value at index min_idx

print(f"The smallest value in the first column is {min_val:.4f} at index {min_idx}")

# Do the same with argmax
max_idx = np.argmax(first_column) # Find the index of the smallest value
max_val = first_column[max_idx]   # Get the value at index min_idx

print(f"The largest value in the first column is {max_val:.4f} at index {max_idx}")

The smallest value in the first column is -9.9871 at index 166
The largest value in the first column is 9.7469 at index 50


## Exercises

### 1. Computing the Mean, Sum and Maximum

You are given an array `A` in the code cell below. 

Compute
1. The mean of all elements in `A` using `np.mean()`,
2. The sum of each row, using `np.sum()`, and
3. The largest value in each column using `np.max()`.

Print the result to verify that it works as you intended. 

You need to use the `axis=` argument for 2. and 3.

The output should be
```
5.0
[ 6 15 24]
[7 8 9]
```

In [28]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Your code here
total_mean = ...
row_sums = ...
column_maxes = ...

# Solution
total_mean = np.mean(A)
row_sums = np.sum(A, axis=1)
column_maxes = np.max(A, axis=0)

print(total_mean)
print(row_sums)
print(column_maxes)

5.0
[ 6 15 24]
[7 8 9]


### 2. Standardize Each Column of a Dataset

You are given a dataset of shape `(200, 5)` stored in the variable `X`. Think of this as 200 observations of 5 different measurements/variables.

We now want to [standardize](https://en.wikipedia.org/wiki/Standard_score#Calculation) each column $X_i$ by applying the transform $\hat{X}_i = \frac{X_i - \hat{\mu}_i}{\hat{\sigma}_i}$ where $\hat{\mu}_i$ and $\hat{\sigma}_i$ are the empirical mean and standard deviation of column $i$, respectively.

Compute the means and standard deviations for each column and standardize `X`. Store the standardized version of `X` in a new variable `X_hat`.

Verify that the mean and standard deviation of each column of `X_hat` is close to 0 and 1, respectively.

**Hints:**

1. Compute the mean and standard deviations for each column by using `np.mean()` and `np.std()` with the argument `axis=0`.
2. Taking advantage of broadcasting, all columns can be standardized simultaneously by simply writing `X_hat = (dataset - mean) / std`.
3. Use `np.mean(X_hat, axis=0)` and `np.std(X_hat, axis=0)` to verify that each column now has mean $\approx 0$ and standard deviation $\approx 1$.

In [29]:
X = np.random.uniform(-10, 10, (200, 5))

# Your code here
mean = ...
std = ...
X_hat = ...

mean = np.mean(dataset, axis=0)
std = np.std(dataset, axis=0)

X_hat = (X - mean) / std
print(X_hat.mean(axis=0))
print(X_hat.std(axis=0))

[-0.07953554 -0.02362517 -0.08733579 -0.11896557 -0.05747687]
[1.00541812 1.08179831 0.96674852 1.01185183 0.97001522]


### 3. Different Ways

Below are three cases where two different expressions give the same result.

Try to understand why they give (approximately) the same answers.

In [30]:
X = np.random.uniform(-10, 10, (200, 5))

# Case 1
print(X.sum(axis=0) / X.shape[0])
print(X.mean(axis=0))

# Case 2
print(X.std())
print(np.mean((X - X.mean())**2) ** 0.5)

# Case 3
print(X.sum())
print((X.mean(0) * len(X)).sum())

[ 0.11155481 -0.89651703 -0.15539797  0.36830602 -0.26709608]
[ 0.11155481 -0.89651703 -0.15539797  0.36830602 -0.26709608]
5.712613046292173
5.712613046292173
-167.83005110852906
-167.83005110852895


### 4. Count With Boolean Arrays

You are given an array `X` with 100000 integers between 0 and 100 in the code cell below.

1. Create a boolean array `ge_50_mask` with the expression `(X > 50)`. This will create an array of the same shape as `X` with `True` or `False` depending on the value in `X` is greater than 50 or not.
2. Print the sum and mean of `ge_50_mask`.

What does the sum and mean of `ge_50_mask` tell us? And why are they approximately, 50000 and 0.5, respectively?

**Note:** When you do `np.sum()` or `arr.sum()` on a boolean array, NumPy will treat `False` as 0 and `True` as 1 and sum these. The same is true for mean and standard deviation.

In [31]:
X = np.random.randint(0, 100, 100000)

# Your code here
ge_50_mask = ...

# Solution
ge_50_mask = (X > 50)
print(ge_50_mask.sum())
print(ge_50_mask.mean())

# It means that approx. half of the random integers are greater than 50

49179
0.49179
