# 1. Creating NumPy Arrays

We start by importing NumPy under the alias `np`.

In [ ]:
import numpy as np

There are numerous ways you can create NumPy arrays. For example, you can create an array from a Python list as follows:

In [2]:
a = [1, 2, 3]
arr = np.array(a)
print(arr)

[1 2 3]


NumPy arrays can be multidimensional. For example, we can create an array `arr` storing the matrix $\begin{pmatrix}1 & 2\\4 & 5\end{pmatrix}$ as follows:

In [3]:
arr = np.array([[1, 2], [4, 5]])
print(arr)

[[1 2]
 [4 5]]


To create an array containing only zeros, we use `np.zeros()`. The `shape` argument expects a tuple determining the shape of the zero array.

In [4]:
arr1 = np.zeros(2) # or np.zeros(shape=(2,))
arr2 = np.zeros(shape=(3, 2)) # 3x2 matrix
arr3 = np.zeros(shape=(2, 3, 2)) # A 3-dimensional array

print(f"arr1 = \n{arr1}\n")
print(f"arr2 = \n{arr2}\n")
print(f"arr3 = \n{arr3}\n")

arr1 = 
[0. 0.]

arr2 = 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

arr3 = 
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]



Similarly, we can create a new array containing only ones using `np.ones()`.

In [5]:
arr2 = np.ones(shape=(3, 2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


The function `np.empty()` creates a new NumPy array and is very fast. But be aware that we do not know which values it will contain, as it just allocates some memory for your array. It is useful if we are going to fill in the values ourselves later.

In [6]:
arr = np.empty(10)

for i in range(10):
    arr[i] = 2 * i

print(arr)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


There is also a dedicated function `np.eye(n)` returning the $n\times n$ identity matrix (ones on the diagonal, zeros everywhere else).

In [7]:
arr = np.eye(4) # 4x4 identity matrix
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


NumPy's `np.arange()` is similar to Python's `range()` function but returns a NumPy array instead of a Python list.

In [8]:
arr1 = np.arange(10)
arr2 = np.arange(2, 7)
arr3 = np.arange(1, 11, 2)
arr4 = np.arange(5, 0, -1)

print(f"arr1 = {arr1}")
print(f"arr2 = {arr2}")
print(f"arr3 = {arr3}")
print(f"arr4 = {arr4}")

arr1 = [0 1 2 3 4 5 6 7 8 9]
arr2 = [2 3 4 5 6]
arr3 = [1 3 5 7 9]
arr4 = [5 4 3 2 1]


To create an evenly spaced 1-dimensional grid, we can use `np.linspace()`. For example, if we want a grid with $11$ points on the interval $[-1, 1]$, we can do as follows:

In [9]:
arr = np.linspace(-1, 1, 11)
print(arr)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


### Shape and data types of NumPy Arrays

There are two important properties of NumPy arrays we should know about. Namely, the `dtype` describing the array's data type and the `shape` describing its shape.

In [10]:
arr = np.array([1, 2, 3])

print(arr)
print(f"dtype: {arr.dtype}")
print(f"shape: {arr.shape}")

[1 2 3]
dtype: int64
shape: (3,)


Here is another example where we use `np.random.uniform()` to create a random NumPy array with shape $(2, 4, 3)$ sampled uniformly from the interval $[0, 1)$. You can read more about NumPy's random module [here (link)](https://numpy.org/doc/stable/reference/random/index.html).

In [11]:
arr = np.random.uniform(size=(2, 4, 3))
print(arr)
print(f"dtype: {arr.dtype}")
print(f"shape: {arr.shape}")

[[[0.47068256 0.23643094 0.62905145]
  [0.52638783 0.90195297 0.94893482]
  [0.89780345 0.00098515 0.67705698]
  [0.95762215 0.7031034  0.81621906]]

 [[0.19276487 0.0719698  0.229159  ]
  [0.13637561 0.87884185 0.52048473]
  [0.86086685 0.72338927 0.55830033]
  [0.91460397 0.63248088 0.23186476]]]
dtype: float64
shape: (2, 4, 3)


NumPy arrays can also store boolean and string values.

In [12]:
arr1 = np.array([[True, False], [False, False]])
arr2 = np.array([["Hel"], ["lo"], ["wo"], ["rld"]])

print("arr1:")
print(arr1)
print(f"dtype: {arr1.dtype}")
print(f"shape: {arr1.shape}")

print("\narr2:")
print(arr2)
print(f"dtype: {arr2.dtype}")
print(f"shape: {arr2.shape}")

arr1:
[[ True False]
 [False False]]
dtype: bool
shape: (2, 2)

arr2:
[['Hel']
 ['lo']
 ['wo']
 ['rld']]
dtype: <U3
shape: (4, 1)


By calling `len()` on a NumPy array, we get the size of the first dimension, so `len(arr)` is equivalent to `arr.shape[0]`.

In [13]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr.shape)
print(arr.shape[0])
print(len(arr))

(4, 2)
4
4


For more details about NumPy data types, see [here (link)](https://numpy.org/doc/stable/user/basics.types.html). To convert an array from one data type to another, one can use `np.ndarray.astype()`. 

In [14]:
arr = np.array(["2.1", "3.6"])
print(arr)

arr = arr.astype(np.float64)
print(arr)

arr = arr.astype(np.int64)
print(arr)

['2.1' '3.6']
[2.1 3.6]
[2 3]


## Exercises

### 1. CSV Data to NumPy Array

The variable `csv_content` contains comma separated CSV data.  Convert this to a NumPy array `arr` of shape `(3, 4)` with `dtype=np.float64`.

In [15]:
csv_content = "1.5,2.2,7.5,0.1\n1.2,7.0,8.9,7.5\n5.5,9.9,9.5,3.4"

# Your code here...
arr = ...

# Solution
arr = np.array([row.split(",") for row in csv_content.split("\n")]).astype(np.float64)

# Automatic tests:
assert (arr == np.array([[1.5, 2.2, 7.5, 0.1], [1.2, 7.,  8.9, 7.5], [5.5, 9.9, 9.5, 3.4]])).all()
assert arr.shape == (3, 4)
assert arr.dtype == np.float64
print("All test passed!")

All test passed!


### 2. Function Values on a Grid

Use `np.linspace()` to create a grid `X` on $[0, 2\pi]$ with $8$ points (NumPy provides $\pi$ as a constant `np.pi`).

Then use `np.cos` on `X` and store the result in a variable `y`. Calling `np.cos(X)` will compute `cos(x)` element-wise on `X` and return an array of the same shape as `X`.

In [16]:
# Your code here
X = ...
y = ...

# Solution
X = np.linspace(0, 2 * np.pi, 8)
y = np.cos(X)

# Automatic tests:
assert np.allclose(X, np.array([0.0, 0.8975979010256552, 1.7951958020513104, 2.6927937030769655, 3.5903916041026207, 4.487989505128276, 5.385587406153931, 6.283185307179586]))
assert np.allclose(y, np.array([1., 0.6234898, -0.22252093, -0.90096887, -0.90096887, -0.22252093, 0.6234898, 1.]))
assert X.shape == y.shape == (8,)
assert X.dtype == y.dtype == np.float_
print("All test passed!")

All test passed!


### 3. Saving and Loading NumPy Arrays

NumPy comes with the functions `np.save()` ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.save.html)) and `np.load()` ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.load.html)).

Create a NumPy array of shape `(4, 2, 2)` containing only ones using `np.ones()` and save it to a file named `ones_array.npy` using `np.save()`.

In [17]:
# Your code here

# Solution
arr = np.ones(shape=(4, 2, 2))
np.save("ones_array.npy", arr)

# Automatic test:
arr = np.load("ones_array.npy")
assert np.allclose(arr, np.array([[[1., 1.], [1., 1.]], [[1., 1.], [1., 1.]], [[1., 1.], [1., 1.]], [[1., 1.], [1., 1.]]]))
print("All test passed!")

All test passed!
