# 5. Matrix and Vector Algebra in NumPy

We start by importing NumPy under the alias `np`.

In [1]:
import numpy as np

NumPy can also perform matrix multiplication and dot products instead of the element-wise operations we have seen so far.

In this example, we first create two matrices $A=\begin{pmatrix}1&2&3\\4&5&6\end{pmatrix}$ and $B=\begin{pmatrix}2&4\\6&8\\10&12\end{pmatrix}$ as NumPy arrays and then compute their [matrix product](https://en.wikipedia.org/wiki/Matrix_multiplication) $AB$. You can either use the shorthand syntax `A @ B` or `np.matmul(A, B)` as these are the same.

For 2D arrays, we can also compute the matrix product by `np.dot(A, B)`.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 4], [6, 8], [10, 12]])

print(A)
print(B)

# These are all equivalent for 2D-arrays:
print(A @ B)
print(np.matmul(A, B))
print(np.dot(A, B))

[[1 2 3]
 [4 5 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 44  56]
 [ 98 128]]
[[ 44  56]
 [ 98 128]]
[[ 44  56]
 [ 98 128]]


We can also do matrix-vector multiplication $Ax$ for a vector $x$. This is just a special case of matrix multiplication, really. 

Notice that if we try to use `*` instead of the `@`, the vector `x` is broadcast, and we end up with a new matrix with the same shape as `A`.

We can also use `np.dot()` to compute the dot-product $x\cdot y$ between two vectors. Alternatively, we can use matrix multiplication for computing the dot product as well since $x\cdot y = x^T y$.

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([1, -1, 2])

print(A @ x)           # Compute Ax matrix-vector product
print(A * x)           # NB! This is not the same as the previous line
print(np.matmul(A, x)) # But this computes Ax ...
print(np.dot(A, x))    # ...and this too.

# Compute dot-product of x and y
y = np.array([-1, 3, 0])
print(np.dot(x, y))
print(x.T @ y) # Equivalent way of computing the dot product

[ 5 11 17]
[[ 1 -2  6]
 [ 4 -5 12]
 [ 7 -8 18]]
[ 5 11 17]
[ 5 11 17]
-4
-4


For more advanced use of `np.matmul()` on higher-dimensional arrays see the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html). Many high-dimensional operations can also be implemented using NumPy's `einsum()` function ([documentation](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html)).

Here are a few more matrix related functions provided by NumPy.

In [4]:
A = np.array([[1, -2, 3], [4, 5, -6], [-7, 8, 9]])

# Get the diagonal of A
print(A.diagonal()) # or np.diag(A)

# Compute trace (sum of diagonal)
print(A.trace())    # or np.trace(A) or A.diagonal().sum()

# Compute the inverse of the matrix A
print(np.linalg.inv(A))

# Print the determinant of A
print(np.linalg.det(A))

[1 5 9]
15
[[ 0.32978723  0.14893617 -0.0106383 ]
 [ 0.0212766   0.10638298  0.06382979]
 [ 0.23758865  0.0212766   0.04609929]]
282.00000000000006


## Exercises

### 1. Element-wise Operations vs. Matrix Multiplication

Perform element-wise multiplication and matrix multiplication for given matrices A and B. Print the results and see how the two operations differ.

In [5]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

# Your code here
elementwise_product = ...
matrix_product = ...

# Solution
elementwise_product = A * B
matrix_product = np.dot(A, B)

print(elementwise_product)
print(matrix_product)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


### Properties of Matrix Multiplication

Recall that matrix multiplication is what we call *associative*. This simply means that $A(BC)=(AB)C$. In other words, multiplying $B$ and $C$ first and then multiply the result with $A$ is the same as first multiplying $A$ and $B$, and then multiplying the result with $C$.

Also recall that matrix multiplication is **not** *commutative*. That is, it is not always true that $AB\neq BA$.

1. Compute $A(BC)$ and $(AB)C$ using NumPy and check that the resulting matrices are equal.
2. Compute $AB$ and $BA$ using NumPy and verify that the two products are different.

In [6]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
C = np.array([[9, 10], 
              [11, 12]])

# Your code here
ABC1 = ...
ABC2 = ...

AB = ...
BA = ...

# Solution
ABC1 = A @ (B @ C)
ABC2 = (A @ B) @ C
print((ABC1 == ABC2).all())

AB = A @ B
BA = B @ A
print((AB == BA).all())

True
False


### 3. Solve Linear System of Equations

Solve the equation $Ax=b$ where $A=\begin{pmatrix}1&4&-1\\2&-5&0\\5&-1&-2\end{pmatrix}$ and $b=\begin{pmatrix}8\\2\\4\end{pmatrix}$ using NumPy.

**Hint:** Use `np.linalg.inv()` to find the inverse $A^{-1}$ of $A$. Then use matrix-vector multiplication to compute $x=A^{-1}Ax=A^{-1}b$ to solve for $x$.

You can compare your answer to the one you get using `np.linalg.solve(A, b)`.

In [7]:
A = np.array([[1,  4, -1],
              [2, -5,  0],
              [5, -1, -2]])

b = np.array([8, 2, 4])

# You code here
A_inv = ...
x = ...

# Solution
A_inv = np.linalg.inv(A)
x = A_inv @ b
print(x)
x_2 = np.linalg.solve(A, b)
print(np.allclose(x_2, x)) # Check that the solutions are approximately equal

[26. 10. 58.]
True
