# 6. Reduction Operations in NumPy

We start by importing NumPy under the alias `np`.

In [1]:
import numpy as np

For this part, let us create a dummy dataset consisting of $200$ rows and $5$ columns by sampling from the uniform distribution  $\mathcal{U}(-10, 10)$.

In [3]:
dataset = np.random.uniform(-10, 10, (200, 5))
print(dataset[:10]) # Print the first 10 rows of our dataset

[[ 1.48373958 -4.32651372  1.06827999  8.75258761  8.07278171]
 [ 6.1894093   7.00737883  7.19258628  1.01259499 -5.22545068]
 [ 6.04844914 -8.50791563 -4.20544008 -3.63610623 -0.64609581]
 [-4.60751896 -1.6970429  -2.52804313  9.04325961 -7.17821479]
 [-2.35046398 -8.4839548   9.07563123 -7.50195687 -5.3579226 ]
 [-9.44954121 -3.30760042 -3.88279973 -1.25967213 -7.5301743 ]
 [-4.73649231 -0.87501205 -4.93589974  3.39420523 -2.93269322]
 [ 5.73608173  3.80497775  7.3021206   6.4746212   1.95900526]
 [-7.73777824  0.16421009 -2.33641246 -1.94923531  2.0651274 ]
 [-1.6182448   8.1075558   1.62904767  0.95468786  6.51121613]]


To compute the mean value, we can use the array method `arr.mean()`.

In [4]:
mean = np.mean(dataset) # or dataset.mean()
print(mean)

-0.04677051796040119


Sometimes, we want to compute the mean for each column or row. We can do this by specifying which dimension we wish to compute the mean along.

In [54]:
# Compute the mean along axis 1. This will take the mean over all columns for each row
# resulting in an array of shape (200,)
row_means = np.mean(dataset, axis=1) # or dataset.mean(axis=1)
print(row_means.shape) # The mean for each row 
print(row_means[:10])  # Print the mean for the first 10 rows

# Similarly, for computing the mean over all rows
col_means = np.mean(dataset, axis=0) # or dataset.mean(axis=0)
print(col_means.shape)
print(col_means)

(200,)
[ 2.41515677  1.43566346 -3.28435282  0.08440053 -1.31403019  1.72374645
 -1.9775666   2.87475501  1.62890465 -1.39555212]
(5,)
[-0.44651098 -0.97507919  0.23033657 -0.79203323  0.28346492]


There are similar functions for computing the sum, minimum, maximum and standard deviation of an array. We can also specify over which axes we want to compute along for these functions.

In [55]:
print(np.sum(dataset, axis=0))      # The sum of each column (compute along row-dimension, axis 0)
print(np.max(dataset))              # The largest value in dataset
print(np.min(dataset, axis=1)[:10]) # The smallest values for the 10 first rows
print(np.std(dataset, axis=0))      # Standard deviation for each column

[ -89.30219674 -195.01583751   46.0673149  -158.40664603   56.69298389]
9.99978912838094
[-5.97699464 -8.54846342 -7.81315859 -7.59519618 -7.06540476  0.12481883
 -5.72363497 -3.00379375 -8.46823746 -7.69588657]
[5.87311268 5.58902189 5.63648335 5.56803812 5.8595576 ]


If we want to find the index of the smallest or largest value, we can use `np.argmin()` and `np.argmax()`, respectively. See the following example where we find the index (and value) of the smallest and largest value in the first column of `dataset`.

In [56]:
first_column = dataset[:, 0]      # Select only the first column

min_idx = np.argmin(first_column) # Find the index of the smallest value
min_val = first_column[min_idx]   # Get the value at index min_idx

print(f"The smallest value in the first column is {min_val:.4f} at index {min_idx}")

# Do the same with argmax
max_idx = np.argmax(first_column) # Find the index of the smallest value
max_val = first_column[max_idx]   # Get the value at index min_idx

print(f"The largest value in the first column is {max_val:.4f} at index {max_idx}")

The smallest value in the first column is -9.8819 at index 107
The largest value in the first column is 9.9166 at index 178


## Exercises

### 1. Computing the Mean, Sum and Maximum

You are given an array `A` in the code cell below. 

Compute
1. The mean of all elements in `A` using `np.mean()`,
2. The sum of each row, using `np.sum()`, and
3. The largest value in each column using `np.max()`.

Print the result to verify that it works as you intended. 

You need to use the `axis=` argument for 2. and 3.

In [57]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Your code here
total_mean = ...
row_sums = ...
column_maxes = ...

# Solution
total_mean = np.mean(A)
row_sums = np.sum(A, axis=1)
column_maxes = np.max(A, axis=0)

print(total_mean)
print(row_sums)
print(column_maxes)

5.0
[ 6 15 24]
[7 8 9]


### 2. Standardize Each Column of a Dataset

You are given a dataset of shape `(200, 5)` stored in the variable `X`. Think of this as 200 observations of 5 different measurements/variables.

We now want to [standardize](https://en.wikipedia.org/wiki/Standard_score#Calculation) each column $X_i$ by applying the transform $\hat{X}_i = \frac{X_i - \hat{\mu}_i}{\hat{\sigma}_i}$ where $\hat{\mu}_i$ and $\hat{\sigma}_i$ are the mean and standard deviation of column $i$, respectively.

Compute the means and standard deviations for each column and standardize `X`. Store the standardized version of `X` in a new variable `X_hat`.

Verify that the mean and standard deviation of each column of `X_hat` is (very close to) 0 and 1, respectively.

**Hints:**

1. Compute the mean and standard deviations for each column by using `np.mean()` and `np.std()` with the argument `axis=0` ("compute along rows").
2. Taking advantage of broadcasting, all columns can be standardized simultaneously by simply writing `X_hat = (dataset - mean) / std`.
3. Use `np.mean(X_hat, axis=0)` and `np.std(X_hat, axis=0)` to verify that each column now has mean $\approx 0$ and standard deviation $\approx 1$.

In [58]:
X = np.random.uniform(-10, 10, (200, 5))

# Your code here
mean = ...
std = ...
X_hat = ...

mean = np.mean(dataset, axis=0)
std = np.std(dataset, axis=0)

X_hat = (X - mean) / std
print(X_hat.mean(axis=0))
print(X_hat.std(axis=0))

[ 0.11633791  0.24840747 -0.01445261  0.05560833 -0.00120868]
[0.98325451 1.03312577 1.0287414  1.00059868 0.99269379]


### 3. Different Ways of Doing Things

Below are three cases where two different expressions give the same result.

Try to understand why they give (approximately) the same answers.

In [59]:
X = np.random.uniform(-10, 10, (200, 5))

# Case 1
print(X.sum(axis=0) / X.shape[0])
print(X.mean(axis=0))

# Case 2
print(X.std())
print(np.mean((X - X.mean())**2) ** 0.5)

# Case 3
print(X.sum())
print((X.mean(0) * len(X)).sum())

[ 0.74353183  0.47480495 -0.97408338 -0.19549168  0.10518622]
[ 0.74353183  0.47480495 -0.97408338 -0.19549168  0.10518622]
5.82451301512215
5.82451301512215
30.789586764258217
30.78958676425826


### 4. Count With Boolean Arrays

You are given an array `X` with 100000 integers between 0 and 100 in the code cell below.

1. Create a boolean array `ge_50_mask` by using `(X > 50)`. This will create an array of the same shape as `X` with `True` or `False` depending on the value in `X` is greater than 50 or not.
2. Print the sum and mean of `ge_50_mask`.

What does the sum and mean of `ge_50_mask` tell us? And why are they approximately, 50000 and 0.5, respectively?

**Note:** When you do `np.sum()` or `arr.sum()` on a boolean array, NumPy will treat `False` as 0 and `True` as 1 and sum these. The same is true for mean and standard deviation.

In [60]:
X = np.random.randint(0, 100, 100000)

# Your code here
ge_50_mask = ...

# Solution
ge_50_mask = (X > 50)
print(ge_50_mask.sum())
print(ge_50_mask.mean())

# It means that approx. half of the random integers are greater than 50

48990
0.4899
